package io.github.vadimbabich.metadata.generator.r2dbc;

import java.io.IOException;

/**
 * Writes one generated Java source file.
 *
 * @author Vadim Babich
 */
public interface JavaClassGenerator extends ClassNameAware {

  /**
   * Header of every generated file. Deliberately carries no date or timestamp, so that regenerating
   * unchanged sources produces byte-identical output.
   */
  String FILE_HEADER =
      "Generated by jpa-metadata-maven-plugin – DO NOT EDIT. Any modifications will be overwritten.";

  void generateSourceFile() throws IOException;
}
