package io.github.vadimbabich.metadata.generator.r2dbc;

import java.io.IOException;

/**
 * Writes one generated Java source file.
 *
 * @author Vadim Babich
 */
public interface JavaClassGenerator extends ClassNameAware {

  /**
   * Header of every generated file. Deliberately carries no date or timestamp, so that regenerating
   * unchanged sources produces byte-identical output.
   */
  String FILE_HEADER =
      "Generated by jpa-metadata-maven-plugin – DO NOT EDIT. Any modifications will be overwritten.";

  /** Spring's own SQL package, which the 1.x shape emits into and references. */
  String SQL_PACKAGE = "org.springframework.data.relational.core.sql";

  String GENERATED_FILE_LOG_FORMAT = "%s.java has been generated at: %s.";

  void generateSourceFile() throws IOException;
}
