// Generated by jpa-metadata-maven-plugin – DO NOT EDIT. Any modifications will be overwritten.
package org.springframework.data.r2dbc.config;

import java.lang.Class;
import java.lang.IllegalArgumentException;
import java.lang.IllegalStateException;
import java.lang.Override;
import java.lang.String;
import org.springframework.beans.BeansException;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.data.mapping.PersistentEntity;
import org.springframework.data.r2dbc.core.R2dbcEntityTemplate;
import org.springframework.data.relational.core.mapping.RelationalPersistentEntity;
import org.springframework.data.relational.core.sql.SqlIdentifier;
import org.springframework.data.relational.core.sql.Table;
import org.springframework.data.util.Lazy;
import org.springframework.stereotype.Component;

@Component
public final class StaticR2dbcEntityTemplateAccessor_ implements ApplicationContextAware {
  private static Lazy<R2dbcEntityTemplate> r2dbcEntityTemplate;

  public static R2dbcEntityTemplate getTemplate() {
    if (r2dbcEntityTemplate == null) {
      throw new IllegalStateException(
          	"StaticR2dbcEntityTemplateAccessor_ has not been initialized yet. Ensure it is registered as a Spring bean.");
    }
    return r2dbcEntityTemplate.get();
  }

  public static <T> RelationalPersistentEntity<T> getPersistentEntity(Class<T> entityType) {
    PersistentEntity<?, ?> persistentEntity = getTemplate()
        	.getConverter()
        	.getMappingContext()
        	.getPersistentEntity(entityType);
    if (persistentEntity == null) {
      throw new IllegalArgumentException("Entity '" + entityType.getSimpleName() +
          	"' is not managed by the current mapping context.");
    }
    return (RelationalPersistentEntity<T>) persistentEntity;
  }

  public static Table getTable(Class entityType) {
    return getTable(entityType, null);
  }

  public static Table getTable(Class entityType, String tableNamePrefix) {
    tableNamePrefix = (tableNamePrefix == null || tableNamePrefix.trim().isEmpty())
        	? "_"
        	: "_" + tableNamePrefix.trim().toLowerCase() + "_";
    SqlIdentifier tableName = getPersistentEntity(entityType).getTableName();
    String alias = tableNamePrefix + entityType.getSimpleName().toLowerCase();
    return Table.aliased(tableName.getReference(), alias);
  }

  @Override
  public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
    r2dbcEntityTemplate = Lazy.of(() -> applicationContext.getBean(R2dbcEntityTemplate.class));
  }
}
