// Generated by jpa-metadata-maven-plugin – DO NOT EDIT. Any modifications will be overwritten.
package org.springframework.data.relational.core.sql;

import java.lang.Class;
import java.lang.IllegalArgumentException;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import org.springframework.data.r2dbc.config.StaticR2dbcEntityTemplateAccessor_;
import org.springframework.data.relational.core.mapping.RelationalPersistentEntity;
import org.springframework.data.relational.core.mapping.RelationalPersistentProperty;
import org.springframework.data.util.Lazy;

public class Column_ implements Expression {
  private final Lazy<Column> delegate;

  public Column_(Class entityType, String fieldName) {
    this.delegate = Lazy.of(() -> getTable(entityType).column(getColumnName(entityType, fieldName)));
  }

  public String name() {
    return delegate.get().getName().getReference();
  }

  @Override
  public String toString() {
    return delegate.get().toString();
  }

  @Override
  public boolean equals(Object other) {
    if (other instanceof Column_ column) { other = column.delegate.get(); };
    return delegate.get().equals(other);
  }

  @Override
  public int hashCode() {
    return delegate.get().hashCode();
  }

  private static String getColumnName(Class entityType, String fieldName) {
    RelationalPersistentEntity<?> persistentEntity = StaticR2dbcEntityTemplateAccessor_.getPersistentEntity(entityType);
    RelationalPersistentProperty persistentProperty = persistentEntity.getPersistentProperty(fieldName);
    if (persistentProperty == null) {
      throw new IllegalArgumentException("Field '" + fieldName + "' for entity '" + entityType.getSimpleName() + "' was not found.");
    }
    return persistentProperty.getColumnName().getReference();
  }

  private static Table getTable(Class entityType) {
    return StaticR2dbcEntityTemplateAccessor_.getTable(entityType);
  }
}
