package io.github.vadimbabich.metadata;

import static org.assertj.core.api.Assertions.assertThat;

import io.github.vadimbabich.metadata.api.JavaLanguageLevel;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.stream.Stream;
import org.apache.maven.project.MavenProject;
import org.junit.jupiter.api.io.TempDir;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

/**
 * Two runs over the same sources must produce byte-identical files, and headers must carry no
 * date or other volatile content.
 */
class GenerationReproducibilityTest {

  @TempDir
  Path firstRun;

  @TempDir
  Path secondRun;

  static List<String> fixturePackages() {
    return List.of(
        "com.example.aggregates",
        "com.example.entities",
        "com.example.inherited",
        "com.example.nested",
        "com.example.readme");
  }

  @ParameterizedTest(name = "package {0}")
  @MethodSource("fixturePackages")
  void givenSameSources_whenGeneratedTwice_thenOutputIsByteIdentical(String packageName)
      throws Exception {
    execute(firstRun, packageName);
    execute(secondRun, packageName);

    List<Path> firstFiles = collectGeneratedFiles(firstRun);
    assertThat(firstFiles).isNotEmpty();

    for (Path first : firstFiles) {
      Path second = secondRun.resolve(firstRun.relativize(first));
      assertThat(second).as("file generated in both runs").exists();
      assertThat(Files.readAllBytes(second))
          .as("byte-identical regeneration of %s", firstRun.relativize(first))
          .isEqualTo(Files.readAllBytes(first));
    }
  }

  @ParameterizedTest(name = "package {0}")
  @MethodSource("fixturePackages")
  void givenGeneratedFile_thenHeaderIsDateFreeAndCarriesCorrectToolName(String packageName)
      throws Exception {
    execute(firstRun, packageName);

    for (Path file : collectGeneratedFiles(firstRun)) {
      String content = Files.readString(file);
      assertThat(content)
          .as("header of %s names the actual plugin artifact", firstRun.relativize(file))
          .contains("Generated by jpa-metadata-maven-plugin");
      assertThat(content)
          .as("header of %s must not embed a generation date", firstRun.relativize(file))
          .doesNotContain("Generated on");
    }
  }

  private void execute(Path outputDirectory, String packageName) throws Exception {
    GenerateEntityMetadataMojo mojo = new GenerateEntityMetadataMojo();

    MavenProject project = new MavenProject();
    project.setFile(new File("./src/test/resources/projects/simple-project/pom.xml"));

    mojo.project = project;
    mojo.languageLevel = JavaLanguageLevel.JAVA_21;
    mojo.sourceDirectory = Path.of("src/main/java");
    mojo.outputDirectory = outputDirectory.toFile();
    mojo.entityMetadataGenerator = "r2dbc";
    mojo.packageName = packageName;

    mojo.execute();
  }

  private List<Path> collectGeneratedFiles(Path root) throws IOException {
    try (Stream<Path> files = Files.walk(root)) {
      return files
          .filter(Files::isRegularFile)
          .filter(path -> path.getFileName().toString().endsWith(".java"))
          .sorted()
          .toList();
    }
  }
}
