// Generated by jpa-metadata-maven-plugin – DO NOT EDIT. Any modifications will be overwritten.
package com.example.model;

import org.springframework.data.r2dbc.config.StaticR2dbcEntityTemplateAccessor_;
import org.springframework.data.relational.core.sql.Column_;
import org.springframework.data.relational.core.sql.Table;

public final class User_ {
  public static final Column_ ID = new Column_(User.class, "id");

  public static final Column_ NAME = new Column_(User.class, "name");

  private User_() {
  }

  public static Table getTable() {
    return StaticR2dbcEntityTemplateAccessor_.getTable(User.class);
  }
}
