// Generated by jpa-metadata-maven-plugin – DO NOT EDIT. Any modifications will be overwritten.
package com.example.model;

import org.springframework.data.r2dbc.config.StaticR2dbcEntityTemplateAccessor_;
import org.springframework.data.relational.core.sql.Column_;
import org.springframework.data.relational.core.sql.Table;

public final class UserAttribute_ {
  public static final Column_ ATTRIBUTE_ID = new Column_(UserAttribute.class, "attributeId");

  public static final Column_ USER_ID = new Column_(UserAttribute.class, "userId");

  public static final Column_ ATTRIBUTE_VALUE = new Column_(UserAttribute.class, "attributeValue");

  private UserAttribute_() {
  }

  public static Table getTable() {
    return StaticR2dbcEntityTemplateAccessor_.getTable(UserAttribute.class);
  }
}
