package io.github.vadimbabich.spike;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * Renders the 1.x metamodel shape as literal text.
 *
 * <p>A fixed template, not a design. The 1.x plugin builds this shape with JavaPoet; the spike
 * reproduces the bytes JavaPoet happens to produce, because byte parity against the committed
 * corpus is the question being answered. Reproducing the shape is not endorsing it — D1 has not
 * frozen anything yet.
 */
final class MetamodelRenderer {

  private static final String HEADER =
      "// Generated by jpa-metadata-maven-plugin – DO NOT EDIT."
          + " Any modifications will be overwritten.";

  private static final List<String> IMPORTS = List.of(
      "org.springframework.data.r2dbc.config.StaticR2dbcEntityTemplateAccessor_",
      "org.springframework.data.relational.core.sql.Column_",
      "org.springframework.data.relational.core.sql.Table");

  /**
   * @param propertyNames property names in declaration order — the golden corpus carries these,
   *     not the {@code @Column} values
   */
  String render(String packageName, String entityName, List<String> propertyNames) {
    String metamodelName = entityName + "_";
    List<String> lines = new ArrayList<>();

    lines.add(HEADER);
    lines.add("package " + packageName + ";");
    lines.add("");

    for (String importedType : IMPORTS) {
      lines.add("import " + importedType + ";");
    }
    lines.add("");

    lines.add("public final class " + metamodelName + " {");

    for (String propertyName : propertyNames) {
      lines.add("  public static final Column_ " + toConstantName(propertyName)
          + " = new Column_(" + entityName + ".class, \"" + propertyName + "\");");
      lines.add("");
    }

    lines.add("  private " + metamodelName + "() {");
    lines.add("  }");
    lines.add("");
    lines.add("  public static Table getTable() {");
    lines.add("    return StaticR2dbcEntityTemplateAccessor_.getTable(" + entityName + ".class);");
    lines.add("  }");
    lines.add("}");

    return String.join("\n", lines) + "\n";
  }

  /**
   * The cross-entity stand-in: a minimal JoinRef surrogate for the staleness experiment. The class
   * literal is a typed reference (deleting the target breaks compilation of a stale file); the
   * property name and type are strings (renaming the target's {@code @Id} leaves a stale file
   * compiling silently) — the same split the real generated {@code JoinRef} would carry.
   */
  String renderReferenceStandIn(
      String packageName,
      String entityName,
      String targetTypeName,
      String targetIdProperty,
      String targetIdType) {

    String metamodelName = entityName + "_";
    List<String> lines = new ArrayList<>();

    lines.add(HEADER);
    lines.add("package " + packageName + ";");
    lines.add("");
    lines.add("public final class " + metamodelName + " {");
    lines.add("  public static final Class<?> REF_TARGET = " + targetTypeName + ".class;");
    lines.add("");
    lines.add("  public static final String REF_TARGET_ID_PROPERTY = \"" + targetIdProperty + "\";");
    lines.add("");
    lines.add("  public static final String REF_TARGET_ID_TYPE = \"" + targetIdType + "\";");
    lines.add("");
    lines.add("  private " + metamodelName + "() {");
    lines.add("  }");
    lines.add("}");

    return String.join("\n", lines) + "\n";
  }

  // Verbatim from R2dbcEntityMetadataGenerator#toConstantName. Byte parity depends on reproducing
  // that two-pass split exactly, not on an equivalent-looking rule.
  private String toConstantName(String propertyName) {
    return propertyName
        .replaceAll("([a-z0-9])([A-Z])", "$1_$2")
        .replaceAll("([A-Z])([A-Z][a-z])", "$1_$2")
        .toUpperCase(Locale.ROOT);
  }
}
