name: Maven CI/CD

on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'bug/**'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    if: github.ref_type == 'branch' && (startsWith(github.ref_name, 'feature/') || startsWith(github.ref_name, 'bug/'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          server-id: github

      - name: Build and test
        run: mvn -B verify

  release:
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for maven-release-plugin to push tags/commits

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
          server-id: github

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/VadimBabich/jpa-metadata-maven-plugin.git

      - name: View settings.xml
        run: cat /home/runner/.m2/settings.xml

      - name: Deploy with Maven Release Plugin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B release:prepare release:perform -Darguments="-DskipTests"